### ISSUE TITLE
Documentation issue: Broken links on the documentation website

### ISSUE THREAD

**Issue by f-person** [TootSDK/TootSDK#129]
Hi! Some links on the documentation website (https://tootsdk.github.io/TootDocs/?v=1) seem to have relative paths. While this works while navigating the docs within the GitHub repo itself, trying to access the links from the website will lead you to the good-old 404 page. Here's an example of such a link: https://tootsdk.github.io/TootDocs/Examples/swiftui-toot/. So far, I've only noticed this with the README; however, I wonder if there are other relative URL paths in the project.

**Comment by davidgarywood** [comment]
Thanks @f-person 🙏

 I suspect this will the only part suffering from this in the docs, as the README in the docs is generated from the README.md in the repo, which is where the relative paths come from in the first place.

I have a plan to look into DocC, as a replacement for Jazzy as I think we could get the docs looking a lot slicker!
