### ISSUE TITLE
TootDataStream.refresh causing duplicate content for home feed

### ISSUE THREAD

**Issue by andrewconlan** [TootSDK/TootSDK#134]
Hi, thanks for all the great work you are doing on this, it's really helpful.
I spotted an issue with refresh which is hard to spot in the SwiftUI-Toot demo but seems to happen consistently, where `min_id` isn't being consistently added to the timelines home request, seems to work as expected for local and federated though.  

Steps to recreate:
Open the SwiftUI-Toot example project
Set client to debugRequests: `self.currentClient?.debugRequests = true`
Launch the project and pull to refresh the home feed in the Browse feed tab
You should see something like:
➡️ 🌏 GET https://mastodon.social/api/v1/timelines/home?min_id=110073176170390408
then pull to refresh again
➡️ 🌏 GET https://mastodon.social/api/v1/timelines/home?
The min_id is no longer set

If you scroll down on the feed you will also see the duplicate content

**Comment by davidgarywood** [comment]
Hi @andrewconlan - thanks for reporting this! Will add it to our todo and it’ll be something I check out soon 🙏

**Comment by andrewconlan** [comment]
thanks David, discovered what the problem is and fixed it here #135  in `TootStream+Posts.swift` when `newHolder.refresh` is called and there is no new content minID is still set but because there is no new results `let minId = items.result.first?.id` is nil
