### ISSUE TITLE
Enhancement request: cancel http requests in response to task cancellation

### ISSUE THREAD

**Issue by daprice** [TootSDK/TootSDK#148]
Currently, if I call any TootClient method that triggers an HTTP request from a Task (e.g. SwiftUI’s `.task(priority:_:)` modifier), then cancel the Task, the URLSessionDataTask responsible for the request does not get cancelled and keeps running. Cancelling the data task in response to cancellation of the concurrency Task would help in several cases I can think of:
- for UI like search, where `TootClient.search` gets called multiple times as the user types, cancelling any previous requests would make the last one more responsive
- when using a client on a slow/unreliable internet connection, cancelling the tasks would keep incomplete requests from building up as the user navigates between views that load data, bogging things down even further
- for things like uploading attachments, the upload should be stopped if the user cancels it rather than silently continuing anyway

I think the current behavior is due to the way TootSDK wraps the callback-based `URLSession.dataTask()` methods in `URLSession+asyncData.swift`. [This StackOverflow answer](https://stackoverflow.com/questions/69506002/cancelling-an-async-await-network-request/70416311#70416311) has an example of how to wrap them like this while also adding a task cancellation handler, but their method requires some extra boilerplate for handling threaded access to the data task because of how the cancellation handler runs in parallel with the task.

**Comment by davidgarywood** [comment]
This is an interesting one. It's definitely worth us taking a look at this. I'm wondering if it's related in part to the same thing I discovered with using Async Sequences as bindings... Tasks don't get cancelled when the object/actor that created them is deallocated (https://davidgarywood.com/swiftui-router-pattern-2-0/ look at the TaskCancellable section).

Looks like something we can fix though, thank you for reporting it 🙏 

In the meantime for search, I would also suggest that you throttle or debounce the search requests to smooth them out a little. Even if we fix this and cancel the data tasks appropriately, you're still at risk of calling the instance unnecessarily and adding to it's load.

**Comment by kkostov** [comment]
@daprice I pushed a possible fix in #152, would it be possible to test if it resolves the issue for you?

**Comment by daprice** [comment]
@kkostov Yes, I tested with a few different TootClient methods and it appears to work perfectly
