### ISSUE TITLE
How to Fetch Replies to a Post?

### ISSUE THREAD

**Issue by fakerybakery** [TootSDK/TootSDK#199]
Hi,
I'm relatively new to TootSDK, so please let me know if I'm missing something obvious.
Is there any way to easily fetch replies to posts?
Thanks in advance!

cc: @kkostov, @davidgarywood

**Comment by kkostov** [comment]
Hi @fakerybakery, 

In the Mastodon API this is referred to as a [Context](https://docs.joinmastodon.org/entities/Context/). Once you have the ID of a post, you can retrieve all posts before and after it using the following:

```swift
let client = TootClient(instanceURL: URL(string: url)!, accessToken: token)
let context = try await client.getContext(id: postId)
```

This is already available, and I also just opened a PR adding an example in the `swiftyadmin` sample you can [check here](https://github.com/TootSDK/TootSDK/pull/200/files#diff-a49e660ac66ac436ea61811ec46fbae517768bb011cfc2ddc503661366c1b77f).
