### ISSUE TITLE
How to Get Posts by Account?

### ISSUE THREAD

**Issue by fakerybakery** [TootSDK/TootSDK#203]
Hi, [now I'm almost sure I'm missing something obvious](https://github.com/TootSDK/TootSDK/issues/202), but is there a way to get posts by a specific user, including their boosted posts? Thanks in advance

**Comment by kkostov** [comment]
@fakerybakery retrieving lists of posts can be done using the timeline feature. We support [several kinds](https://github.com/TootSDK/TootSDK/blob/main/Sources/TootSDK/Models/Timeline/Timeline.swift#L7C7-L7C7) of timelines depending on the context and kind of posts that need to be retrieved.

Given a user identifier, you can use `Timeline.user(query)` to create a timeline query for their posts e.g. `.user(UserTimelineQuery(userId: userID))`. We have a facility function to build this query in one go if you prefer that: `Timeline.user(userID: "..")`.

Given a timeline query, you can use the `getTimeline(:)` [method](https://github.com/TootSDK/TootSDK/blob/main/Sources/TootSDK/TootClient/TootClient%2BTimeLine.swift#L69) like so:

```swift
let timelinePage = try await client.getTimeline(.user(userID: "the user id"))
```  

This will give you a page of the timeline. Depending on your use case, you may want to retrieve all pages with a loop that looks like something like this:

```swift
var pagedInfo: PagedInfo? = nil
var hasMore = true

while hasMore {
  let page = try await client.getTimeline(.user(userID: "my user id"), pageInfo: pagedInfo)
  for post in page.result {
    print(post.content!)
  }
  hasMore = page.hasPrevious
  pagedInfo = page.previousPage
}
```
