### ISSUE TITLE
TootClient.getPendingFollowRequests doesn't return PagedResult

### ISSUE THREAD

**Issue by technicat** [TootSDK/TootSDK#226]
The newly introduced TootClient.getPendingFollowRequests takes a PageInfo but doesn't return a PagedResult so it can't be paged. For now, I'm using a slightly adjusted (and renamed) version that just differs in returning PagedResult and calling fetchPagedQuery at the end

```swift
 func getFollowRequests(_ pageInfo: PagedInfo? = nil, limit: Int? = nil) async throws -> PagedResult<[Account]> {
        try requireFeature(.followRequests)
        let req = HTTPRequestBuilder {
            $0.url = getURL(["api", "v1", "follow_requests"])
            $0.method = .get
            $0.query = getQueryParams(pageInfo, limit: limit)
        }
        return try await fetchPagedResult(req)
    }
```

**Comment by kkostov** [comment]
@technicat Thank you for suggesting the snippet, I deprecated the old method and added the paginated implementation. Please note that while testing, some flavours ignored the pagination and returned all requests anyway so I added this to the comment as well.
