### ISSUE TITLE
list of apps using tootsdk

### ISSUE THREAD

**Issue by technicat** [TootSDK/TootSDK#230]
would be cool to have a list of apps that use tootsdk, perhaps in the readme (I can think of three apps, but surely there are more)

**Comment by derspyy** [comment]
ooh! which ones? i've been dying to know!

**Comment by technicat** [comment]
> ooh! which ones? i've been dying to know!

Pipilo and Topiary, currently on the App Store, are both by contributors here, so I assume they use TootSDK. And there's mine, Fedicat, but still in Testflight.

**Comment by kkostov** [comment]
That's a great idea @technicat. We'd need a cool way to let folks know they can put forward their app. What do you think @davidgarywood?

**Comment by davidgarywood** [comment]
I love it - can we just add them to the `README.md`, and authors can raise a PR to add their app and it's link?

**Comment by kkostov** [comment]
They're now in the README. I started working on something to make the list even better. Coming soon ...
