### ISSUE TITLE
escaping slashes in debug output

### ISSUE THREAD

**Issue by technicat** [TootSDK/TootSDK#236]
I just noticed recently that when I have TootClient.debugResponse set the URLs have escape backslashes in them which I now realize are in some of the test data that I added, like this

```json
"preview_url" : "https:\/\/media.universeodon.com\/media_attachments\/files\/110\/884\/868\/918\/054\/337\/small\/93d235b25788c9fd.jpeg",
```
Adding .withoutEscapingSlashes to the pretty printer seems to fix it. Any reason not to add it?

```swift
var prettyPrintedJSONString: NSString? {
        guard let object = try? JSONSerialization.jsonObject(with: self, options: []),
              let data = try? JSONSerialization.data(withJSONObject: object, options: [.prettyPrinted, .withoutEscapingSlashes]),
```

**Comment by kkostov** [comment]
@technicat good idea! 
I don't think there is a reason, it just didn't' occur to me to do it before.

**Comment by kkostov** [comment]
This is already merged
