### ISSUE TITLE
Inconsistent order of media attachments for scheduled posts

### ISSUE THREAD

**Issue by mikakruschel** [TootSDK/TootSDK#246]
Hey 👋,
I'm building an app to schedule posts and noticed that the `mediaAttachments` and `params.mediaIds` in `ScheduledPost` have inconsistent ordering. `params.mediaIds` appears to have the correct order, while `mediaAttachments` are sorted numerically by their id. I'm not sure whether this would be considered to be a bug in the Mastodon API, but it would be nice to have consistent ordering in TootSDK. If you agree, I can create a pull request to add a decodable implementation of `ScheduledPost` that fixes the ordering based on `params.mediaIds`.

**Comment by davidgarywood** [comment]
Hey 👋 

I’d definitely be interested to see a PR from you for this!
