### ISSUE TITLE
PostsTests.swift only has ScheduledPost tests

### ISSUE THREAD

**Issue by technicat** [TootSDK/TootSDK#248]
Should be renamed to avoid Post and ScheduledPost tests ending up in the same file. Maybe ScheduledPostsTests.swift?

**Comment by technicat** [comment]
well ok but it's already a big file and it's confusing to have decode tests of two different classes in the same file, Post and ScheduledPost are distinctly different

**Comment by kkostov** [comment]
Ok, that's a fair point. After merging your translation PR I will split them up.
