### ISSUE TITLE
CONTRIBUTING.md - note about anonymizing test data

### ISSUE THREAD

**Issue by technicat** [TootSDK/TootSDK#255]
there should be a note about how test data should be anonymized and examples how to do it (I've just been copying from previous test data and removing chunks that I don't want to bother with) with a standard fake domain, for example, so people don't accidentally use a real one, maybe

https://en.wikipedia.org/wiki/Example.com

**Comment by davidgarywood** [comment]
Addressing in PR: https://github.com/TootSDK/TootSDK/pull/261
