### ISSUE TITLE
Store or return the `Instance` struct from `TootClient.connect()`

### ISSUE THREAD

**Issue by daprice** [TootSDK/TootSDK#266]
Right now, `TootClient.connect()` (and by extension, `init(connect:clientName:session:accessToken:scopes:)`) makes an API call with `getInstanceInfo()` but only stores the instance flavor and discards the `Instance` struct. If my app needs that struct, I have to immediately call `getInstanceInfo()` a second time.

Ideally, `connect()` would either store the `Instance` struct as a property of `TootClient`, and/or return it directly (in which case `init(connect:clientName:session:accessToken:scopes:)` also needs to return it) so the app can make use of it.

**Comment by technicat** [comment]
what I do is init TootClient without calling connect and instead call this (and I have a wrapper object called Session around TootClient for managing extra state including that returned Instance)

```swift
extension TootClient {

  public func getInstance() async throws -> Instance {
    let instance = try await getInstanceInfo()
    flavour = instance.flavour
    return instance
  }
}
```

**Comment by kkostov** [comment]
We always try to minimise internal state of `TootClient` - if anything is to be persisted, it's up to the consuming app to manage the lifecycle as we can't predict that.

That we rely on `getInstanceInfo` to detect the flavour should be seen as an implementation detail of the library. If we find a way to understand the flavour without invoking the method then both `connect` and any initialisers would adopt the new approach and spare us the extra API call (Any suggestions on how to achieve this are more than welcome).

So you're both definitely on the right track - if your app requires instance information, you should invoke `getInstanceInfo` when needed and keep a copy of `Instance` for as long as your app needs it.
