### ISSUE TITLE
Cannot build in Xcode 16 

### ISSUE THREAD

**Issue by vincentneo** [TootSDK/TootSDK#283]
Because of https://github.com/karwa/swift-url/issues/186, I am not sure how to solve the ambiguity issue (yet).

**Comment by karwa** [comment]
I've released 0.4.2 which should fix the issue. If you tell Xcode to fetch the latest package versions, you should get the new release automatically. I'd also recommend bumping the version specified in TootSDK's `Package.swift` to ensure that everybody gets it.

![image](https://github.com/TootSDK/TootSDK/assets/5254025/03bade88-53f0-42a8-8e7e-98c48f102b60)

**Comment by kkostov** [comment]
Thank you @karwa 🤩 ! I will make a PR right away.
