### ISSUE TITLE
Complete Mastodon API 4.0 coverage

### ISSUE THREAD

**Issue by davidgarywood** [TootSDK/TootSDK#29]
### Timelines
- [ ] Retrieve timelines for followed hashtags 
- [x] Local (instance) timeline
- [x] Federated timeline
- [x] Lists
- [x] Viewing favourite posts
- [x] Viewing user's bookmarks

### Account
- [x] Register an account
- [ ] Update account credentials
- [x] Get account’s statuses
- [x] Get account’s followers
- [x] Get account’s following
- [x] Get account’s featured tags
- [ ] Get lists containing this account
- [ ] Feature account on your profile
- [ ] Unfeature account from profile
- [ ] Set private note on profile
- [ ] Check relationships to other accounts
- [ ] Find familiar followers
- [ ] Search for matching accounts
- [ ] Lookup account ID from Webfinger address

### Search
- [x] Implementation of search API

**Comment by kkostov** [comment]
@davidgarywood maybe we should update the todo list and refine for v4.1?

**Comment by davidgarywood** [comment]
@heyjaywilson  - with version 0.22.0 onwards, we have the local (public timeline), and the federated time line. You can use `[getFederatedTimeline](https://tootsdk.github.io/TootDocs/Classes/TootClient.html#/s:7TootSDK0A6ClientC20getFederatedTimeline_5limitAA11PagedResultVySayAA4PostCGGAA0H4InfoVSg_SiSgtYaKF)` on TootClient, or you can use the TootStream with `. timeLineFederated`

This is a really recent update though!

**Comment by daprice** [comment]
What about [hashtag timelines](https://docs.joinmastodon.org/methods/timelines/#tag)? Not sure if that’s what’s meant by “retrieve timelines for followed hashtags” in the checklist, but this API endpoint is for any hashtag and not just followed ones.

**Comment by kkostov** [comment]
@daprice, yes indeed, the hashtag timeline is one of the timelines still to add
