### ISSUE TITLE
Decoding error when getting Instance information from Pixelfed server

### ISSUE THREAD

**Issue by JoshHrach** [TootSDK/TootSDK#300]
Pixelfed server is running latest version (0.12.3 as of this bug).

Attempting to call `client.getInstanceInfo()` throws a decoding error:
> decodingError("Type \'Int\' mismatch:Expected to decode Int but found a string instead.\n codingPath:[CodingKeys(stringValue: \"stats\", intValue: nil), CodingKeys(stringValue: \"statusCount\", intValue: nil)]")

This seems related to a recent change to the Pixelfed API (that's likely a bug, per [this issue](https://github.com/pixelfed/pixelfed/issues/5178), as it deviates from the Mastodon spec).

In a case like this, I don't know if a workaround makes sense in this SDK or wait and see if they address this bug in a future release.

**Comment by Tunous** [comment]
I would recommend adding a workaround. Fallback attempt to parse Int from String won't break anything.

**Comment by technicat** [comment]
Yeah, they used to fix API issues quickly but lately, I guess because they've been busy with other projects, it's been slower. There's another open bug I reported in April where boosting would wipe out the favourited flag in the returned status and vica versa.

I'm using a variation of `decodeIntForString` just for this workaround, which seems excessive for just this once case, but it gets the number.

```swift
func decodeOptionalIntFromString(forKey key: Key) throws -> Int? {
    do {
      return try decodeIfPresent(Int.self, forKey: key)
    } catch {  // type mismatch
      let string = try decode(String.self, forKey: key)
      if let int = Int(string) {
        return int
      }
      throw error
    }
  }
```

**Comment by kkostov** [comment]
Thank you all 🙌!
I agree that it would be nice if Pixelfed can improve this on their side. For now, it's a minor adjustment that would help everyone using TootSDK. Please try version `8.2.1`. 

PS: I also snuck another Sendable warning fix, I hope we got them all 😂.

**Comment by JoshHrach** [comment]
Tested and works well. Thanks for the quick turnaround, @kkostov!

**Comment by technicat** [comment]
fixed now in pixelfed, too

https://github.com/pixelfed/pixelfed/commit/dcd95d687c98f27b853835ee9bfd88dcf655e868
