### ISSUE TITLE
Decoding error, on errors w/ WebSocket against Mastodon.social

### ISSUE THREAD

**Issue by helje5** [TootSDK/TootSDK#304]
I'm playing w/ the WebSocket support. Along those lines:
```swift
      let socket = try await client.beginStreaming()
      try await socket.sendQuery(.init(.subscribe, timeline: .user))
      try await socket.sendQuery(.init(.subscribe, timeline: .userNotification))
      try await socket.sendQuery(.init(.subscribe, timeline: .direct))
```
I sometimes get various TLS failures, even though I pass in a URLSession that ignores such, but apart from that, if it goes through, it seems to trigger an error which results in:
```
(lldb) po error
▿ DecodingError
  ▿ keyNotFound : 2 elements
    - .0 : CodingKeys(stringValue: "stream", intValue: nil)
    ▿ .1 : Context
      - codingPath : 0 elements
      - debugDescription : "No value associated with key CodingKeys(stringValue: \"stream\", intValue: nil) (\"stream\")."
      - underlyingError : nil
```
This comes from:
```swift
extension StreamingEvent: Decodable {
    public init(from decoder: any Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        guard let timeline = StreamingTimeline(rawValue: try values.decode([String].self, forKey: .stream)) else {
```
Apparently in my case an error happens and has those keys:
- error
- status
So maybe that init should check for an optional .stream key, and if that's missing check for error&status and raise an appropriate exception.

**Comment by helje5** [comment]
Added this:
```swift
    enum CodingKeys: String, CodingKey {
        case stream
        case event
        case payload
        case error // <==
        case status // <==
    }
```
and this:
```swift
        guard let value = try values.decodeIfPresent([String].self, forKey: .stream),
          let timeline = StreamingTimeline(rawValue: value) else
      {
          if let error = try? values.decodeIfPresent(Int.self, forKey: .status) {
            print("STATUS:", error)
          }
          if let error = try? values.decodeIfPresent(String.self, forKey: .error) {
            print("ERROR:", error)
          }
```
The status is 400 and the error is "Unknown stream type".

**Comment by kkostov** [comment]
@helje5 you should also be able to subscribe to a stream without manually calling beginStreaming:

```swift
// open a socket to a specific timeline
let stream = try! await client.streaming.subscribe(to: .userNotification)

do {
    // listen for events
    for try await event in stream {
        print("got event")
        switch event {
        case .connectionUp:
            //...
        case .connectionDown:
            //...
        case .receivedEvent(let eventContent):
            //...
        }
    }
} catch {
    print(String(describing: error))
}
```

cf. [Example](https://github.com/TootSDK/TootSDK/blob/main/Examples/swiftyadmin/Sources/swiftyadmin/Streams/StreamEvents.swift)

Some investigation is required as to why the `.userNotification` timeline is not being accepted by the server. The other two seem to be working as expected.

**Comment by helje5** [comment]
Hm, thanks, but wouldn't I want to listen/subscribe to multiple things? Why would I use multiple streams for such, I have to handle all cases anyways?

**Comment by kkostov** [comment]
Neat, I will have a look.
We can definitely provide a facility where you get a swift stream from multiple timelines e.g. #308 

```swift
let stream = try! await client.streaming.subscribe(to: [.userNotification, .public])

do {
    // listen for events
    for try await event in stream {
        print("got event")
        switch event {
        case .connectionUp(let timeline):
            //...
        case .connectionDown(let timeline):
            //...
        case .receivedEvent(let timeline, let eventContent):
            //...
        }
    }
} catch {
    print(String(describing: error))
}
``` 

Under the hood though, it will always be a socket per timeline.

**Comment by helje5** [comment]
Oh, it is a WebSocket per timeline, interesting. That seems wasteful :-)

**Comment by helje5** [comment]
So I guess we keep this open for the `userNotification` issue. I improved the decoding in my PR.

**Comment by kkostov** [comment]
Yes - I'm not sure why Mastodon doesn't like this timeline. I've planned some time to debug this tomorrow. I also want to test it with Pleroma/Akkoma as they usually have good validation errors and may reveal some hints as to what's going wrong.

**Comment by kkostov** [comment]
@helje5 version `8.5.0` is released with your fixes and some other improvements, feel free to take it for a spin!

**Comment by daprice** [comment]
@kkostov @helje5 StreamingClient (i.e. `tootClient.streaming`) does share a single WebSocket for all timelines.

The UserNotification thing was a typo in the rawValue of that timeline; I opened a PR for the fix
