### ISSUE TITLE
Pleroma followByURI not working

### ISSUE THREAD

**Issue by davidgarywood** [TootSDK/TootSDK#34]
Pleroma followByURI is not working.

We have a private function:

```
    /// Pleroma Specific. This follows an account by URI and returns the account being followed
    /// - Parameter uri: account name on the instance you're on or a users URI (e.g @test@instance.test)
    /// - Returns: the Account being followed
    private func pleromaFollowAccountURI(by uri: String) async throws -> Account {
        let params = PleromaFollowByURIParams(uri: uri)
        
        let req = try HttpRequestBuilder {
            $0.url = getURL(["api", "v1", "follows"])
            $0.method = .post
            $0.body = try .json(params)
        }
        return try await fetch(Account.self, req)
    }
```

This is used to follow the account requested by URI, and is an attempt to implement this Pleroma API call: https://api.pleroma.social/#operation/AccountController.follows

When testing with a Pleroma user and instance, attempting to follow my own user @davidgarywood@social.davidgarywood.com either by the username, or via https://social.davidgarywood.com/@davidgarywood or https://social.davidgarywood.com/davidgarywood  I receive this response from Pleroma:

{
  "error" : "Record not found"
}

**Comment by kkostov** [comment]
This doesn't seem to persist anymore.
