### ISSUE TITLE
Signing in to mastadon.social error

### ISSUE THREAD

**Issue by adrianthomas** [TootSDK/TootSDK#99]
When you try to sign in to mastadon.social, it has suddenly started throwing an error:
`[TootSDK bug] There was an error decoding incoming data:
context: Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around line 1, column 0." UserInfo={NSDebugDescription=Invalid value around line 1, column 0., NSJSONSerializationErrorIndex=0})).
`
Other servers don't seem to have this problem.

**Comment by adrianthomas** [comment]
Looks like this was temporary so presumably a server issue. 
Perhaps these could pop an error message, currently it just silently fails.

**Comment by kkostov** [comment]
Thank you for reporting this!

The message `[TootSDK bug] There was an error decoding incoming data...` is printed when a network request succeeds (HTTP status code is in the 2xx range) but the response body is not formatted correctly/does not contain a correct payload.

We will need additional information about the server response to improve the error message. If you encounter this again, could you please include the traces from `TootClient` after calling `client.debugOn()`? This will include several lines starting with the `⬅️` emojis that include all headers and the raw body response from the server. Thank you 🙌!
